#a makefile which is going to create the running programs for given source files
ex01:					con01.cpp
						g++ -g -Wall -o con01.run con01.cpp

ex02:					con02.cpp
						g++ -g -Wall -o con02.run con02.cpp

ex03:					con03.cpp
						g++ -g -Wall -o con03.run con03.cpp

ex04:					con04.cpp
						g++ -g -Wall -o con04.run con04.cpp

clean:
						rm con*.run
