ARGUMENTS=-g3 -Wall
SOURCE=22_csv.cpp 22_main.cpp 22_csv.hpp
TARGET=application

CPP:
							@g++ $(ARGUMENTS) $(SOURCE) -o $(TARGET)
							$(info application (for C++) has been created...)

clean:
							@rm $(TARGET)
							$(info application removed...)