task01:							ExceptionTest.cpp
								g++ -g -Wall -o exTest01.run ExceptionTest.cpp

task02:							ExceptionTest.cpp ExceptionTest.hpp
								g++ -g -Wall -o exTest02.run ExceptionTest.cpp ExceptionTest.hpp

clean:
								rm *.run
