all:				friend_keyword.hpp friend_keyword.cpp friend_point.cpp friend_runner.cpp
					g++ -g -Wall -o friend_keyword.run friend_keyword.hpp friend_keyword.cpp friend_point.cpp friend_runner.cpp

clean:
					rm friend_keyword.run
