all:						write read

read:						fileRead.cpp
							g++ -g -Wall -o fileReader.run fileRead.cpp

write:						fileWrite.cpp
							g++ -g -Wall -o fileWriter.run fileWrite.cpp

clean:
							rm *.run
